name: Publish ghpr-pkg to GitHub Packages
on:
  workflow_dispatch:
    inputs:
      loglevel:
        description: 'Log level for npm publish (default: notice)'
        required: false
        default: 'notice'
        type: choice
        options:
          - notice
          - silent
          - error
          - warn
          - http
          - info
          - verbose
          - silly

  pull_request:
    paths:
      - .github/workflows/ghpr-pkg.yml
      - workspaces/ghpr-pkg/**
  push:
    paths:
      - .github/workflows/ghpr-pkg.yml
      - workspaces/ghpr-pkg/**
    branches:
      - main

jobs:
  publish:
    environment:
      name: publish
      url: https://github.com/hashtagchris/npm-test-packages/pkgs/npm/ghpr-pkg
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Determine npm loglevel
        uses: actions/github-script@v7
        with:
          script: |
            let loglevel = 'notice' // default loglevel

            if (context.payload.inputs?.loglevel) {
              console.log('Found loglevel in workflow dispatch inputs')
              loglevel = context.payload.inputs.loglevel
            }
            else if (context.payload.head_commit?.message) {
              const match = context.payload.head_commit.message.match(/^(npm-)?loglevel:\s*(\w+)/m)
              if (match && match[1]) {
                console.log('Found loglevel in head commit message:', match[2])
                loglevel = match[2]
              }
            }

            console.log(`Setting npm loglevel to '${loglevel}'`)
            core.exportVariable('LOGLEVEL', loglevel)

      # Adds NODE_AUTH_TOKEN env var reference to .npmrc file
      - uses: actions/setup-node@v4
        with:
          registry-url: https://npm.pkg.github.com

      - name: Publish package
        working-directory: workspaces/ghpr-pkg
        run: |
          npm publish --registry=https://npm.pkg.github.com --access=public --loglevel=$LOGLEVEL
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
