name: Publish hashtagchris-provenance-test package
on:
  workflow_dispatch:
    inputs:
      loglevel:
        description: 'Log level for npm publish (default: notice)'
        required: false
        default: 'notice'
        type: choice
        options:
          - notice
          - silent
          - error
          - warn
          - http
          - info
          - verbose
          - silly

  pull_request:
    paths:
      - .github/workflows/hashtagchris-provenance-test.yml
      - workspaces/hashtagchris-provenance-test/**
  push:
    paths:
      - .github/workflows/hashtagchris-provenance-test.yml
      - workspaces/hashtagchris-provenance-test/**
    branches:
      - main

jobs:
  publish:
    environment:
      name: hashtagchris-provenance-test
      url: https://npmjs.com/package/hashtagchris-provenance-test
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set log level
        run: |
          if [ -z "${{ github.event.inputs.loglevel }}" ]; then
            echo "LOGLEVEL=notice" >> $GITHUB_ENV
          else
            echo "LOGLEVEL=${{ github.event.inputs.loglevel }}" >> $GITHUB_ENV
          fi

      # Adds NODE_AUTH_TOKEN env var reference to .npmrc file
      - uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org

      - name: Install newest npm
        run: |
          sudo npm install -g npm@latest

      - name: Check npm version
        run: |
          npm --version

      - name: Publish package
        working-directory: workspaces/hashtagchris-provenance-test
        run: |
          npm publish --provenance --access=public --loglevel=$LOGLEVEL
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
