name: Publish hashtagchris-provenance-test package
on:
  workflow_dispatch:
    inputs:
      loglevel:
        description: 'Log level for npm publish (default: notice)'
        required: false
        default: 'notice'
        type: choice
        options:
          - notice
          - silent
          - error
          - warn
          - http
          - info
          - verbose
          - silly

  pull_request:
    paths:
      - .github/workflows/hashtagchris-provenance-test.yml
      - workspaces/hashtagchris-provenance-test/**
  push:
    paths:
      - .github/workflows/hashtagchris-provenance-test.yml
      - workspaces/hashtagchris-provenance-test/**
    branches:
      - main

jobs:
  publish:
    environment:
      name: hashtagchris-provenance-test
      url: https://npmjs.com/package/hashtagchris-provenance-test
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Inspect triggering GitHub event
        run: |
          cat $GITHUB_EVENT_PATH

      - uses: actions/checkout@v4

      - name: Determine npm loglevel
        uses: actions/github-script@v7
        with:
          script: |
            // check workflow dispatch inputs
            if (context.inputs?.loglevel) {
              console.log(`Setting loglevel to ${context.inputs.loglevel}`)
              core.setEnv('LOGLEVEL', context.inputs.loglevel)
              return
            }

            // check the commit message
            if (context.head_commit?.message) {
              const match = context.head_commit.message.match(/^(npm-)?loglevel:\s*(\w+)/m)
              if (match && match[1]) {
                console.log(`Setting loglevel to ${match[1]}`)
                core.setEnv('LOGLEVEL', match[1])
                return
              }
            }

            // default to 'notice'
            console.log('No loglevel specified, defaulting to "notice"')
            core.setEnv('LOGLEVEL', 'notice')

      # Adds NODE_AUTH_TOKEN env var reference to .npmrc file
      - uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org

      - name: Install newest npm
        run: |
          sudo npm install -g npm@latest

      - name: Do a non-global install of the npm cli with OIDC support
        run: |
          mkdir -p /tmp/npm-cli
          cd /tmp/npm-cli
          npm init -y
          npm install npm/cli#oidc
          ln -s /tmp/npm-cli/node_modules/.bin/npm /tmp/npm
          /tmp/npm --version

      - name: Check npm version
        run: |
          /tmp/npm --version

      - name: Publish package
        working-directory: workspaces/hashtagchris-provenance-test
        run: |
          /tmp/npm publish --provenance --access=public --loglevel=$LOGLEVEL
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
