name: Publish hashtagchris-oidc-test package
on:
  workflow_dispatch:
    inputs:
      version_increment:
        description: 'Version increment type (major, minor, patch)'
        required: false
        default: 'none'
        type: choice
        options:
          - none
          - patch
          - minor
          - major
  pull_request:
    paths:
      - .github/workflows/publish-hashtagchris-oidc-test.yml
      - workspaces/hashtagchris-oidc-test
  push:
    paths:
      - .github/workflows/publish-hashtagchris-oidc-test.yml
      - workspaces/hashtagchris-oidc-test
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      # Adds NODE_AUTH_TOKEN env var reference to .npmrc file
      - uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org
          check-latest: true

      - name: Debug npm install
        continue-on-error: true
        run: |
          which npm
          npm --version
          sudo npm install -g npm@latest
          npm --version
          which npm
          ls -la $(which npm)
          ls -la /usr/local/lib/node_modules
          ls -la /usr/local/lib/node_modules/npm
          ls -la /usr/local/lib/node_modules/npm/bin
          ls -la /usr/local/lib/node_modules/npm/bin/npm-cli.js

      # Temporary, until actions/setup-node sets up an npm cli with OIDC support
      - name: Update to the latest version of the npm cli with OIDC support
        continue-on-error: true
        run: |
          sudo npm install -g npm/cli#oidc

      - name: Do a non-global install of the npm cli with OIDC support
        run: |
          mkdir -p /tmp/npm-cli
          cd /tmp/npm-cli
          npm install npm/cli#oidc
          ls -la /tmp/npm-cli/node_modules
          ls -la /tmp/npm-cli/node_modules/npm

          /tmp/npm-cli/node_modules/npm/bin/npm-cli.js --version

      - name: Increment version
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version_increment != 'none' }}
        working-directory: workspaces/hashtagchris-oidc-test
        id: increment_version
        run: |
          /tmp/npm-cli/node_modules/npm/bin/npm-cli.js version ${{ github.event.inputs.version_increment }}

      - name: Install dependencies
        working-directory: workspaces/hashtagchris-oidc-test
        run: |
          ls -la /tmp/npm-cli/node_modules/npm/bin/npm-cli.js
          /tmp/npm-cli/node_modules/npm/bin/npm-cli.js ci

      - name: Publish
        working-directory: workspaces/hashtagchris-oidc-test
        run: |
          # npm publish
          # npm publish --loglevel=silly
          ls -la /tmp/npm-cli/node_modules/npm/bin/npm-cli.js
          /tmp/npm-cli/node_modules/npm/bin/npm-cli.js publish --loglevel=silly
